
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gkm-2019
    type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter

    initialSize: 5
    minIdle: 5
  data:
    rest:
      base-path: /api
#      配置redis 本次作为缓存
  redis:
    host: 127.0.0.1
#    schema:
#      - classpath:springboot.sql
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml



# 试下热部署
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: cout=countSql

